name: CodeControl
on:
  push:
jobs:
  quality:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup `terraform`
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.2
          terraform_wrapper: true
      - name: Version of Terraform    
        run: terraform version
      - name: Check format of Terrraform files
        run: terraform fmt -check
  docs:
    runs-on: ubuntu-20.04
    container:
      image: raphaeldegail/terraform-docs:0.16.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Terraform docs
        run: terraform-docs --output-check .